/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_admin_testndk_Load */

#ifndef _Included_com_example_admin_testndk_Load
#define _Included_com_example_admin_testndk_Load
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_admin_testndk_Load
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_testndk_Load_addInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_admin_testndk_Load
 * Method:    mulDouble
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_admin_testndk_Load_mulDouble
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_example_admin_testndk_Load
 * Method:    bigger
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_admin_testndk_Load_bigger
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_example_admin_testndk_Load
 * Method:    addString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_admin_testndk_Load_addString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_admin_testndk_Load
 * Method:    intArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_admin_testndk_Load_intArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_admin_testndk_Load
 * Method:    doubleArray
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_example_admin_testndk_Load_doubleArray
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     com_example_admin_testndk_Load
 * Method:    stringArray
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_admin_testndk_Load_stringArray
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
